#!/bin/bash

#SBATCH --job-name=ASPArc
#SBATCH --partition=gpu_h100
#SBATCH --time=02:00:00
#SBATCH --gpus=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --chdir=/home/dlindberg/Projects/asp-arc
#SBATCH --output=outputs/slurm_output_%A.out

# NOTE: Before running this job for the first time, make sure the venv exists:

module purge
module load 2025
module load CUDA/12.8.0
module load Python/3.13.5-GCCcore-14.3.0

mkdir -p outputs caches logs

source .venv/bin/activate

python3 -m main \
    --dataset arc-v1-training \
    --num 3 \
    --engine qwen36-35B

echo ""
echo "Job complete."
