#!/bin/bash

#SBATCH --job-name=ASPArcSingle
#SBATCH --partition=gpu_h100
#SBATCH --time=01:00:00
#SBATCH --gpus=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --chdir=/home/dlindberg/Projects/asp-arc
#SBATCH --output=outputs/slurm_single_%A.out

module purge
module load 2025
module load CUDA/12.8.0
module load Python/3.13.5-GCCcore-14.3.0

source .venv/bin/activate

python3 main_single.py --dataset arc-v1-training --num 3
